### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by AMV007** [Deamon5550/Despector#16]
java -jar despector-0.1.0-SNAPSHOT-base.jar in out
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Lists
        at org.spongepowered.despector.emitter.format.EmitterFormat.<init>(EmitterFormat.java:57)
        at org.spongepowered.despector.emitter.format.EmitterFormat.<clinit>(EmitterFormat.java:438)
        at org.spongepowered.despector.Despector.main(Despector.java:181)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Lists
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 3 more

**Comment by SubOptimal** [comment]
You probably build with `./gradlew jar` (only the jar containing the main classes of the project itself) instead of building with `gradlew build`(build also a jar which contains also the dependencies).


> Build tasks
> -----------
> 
>
>assemble - Assembles the outputs of this project.
>**build - Assembles and tests this project.**
>buildDependents - Assembles and tests this project and all projects that depend on it.
>buildNeeded - Assembles and tests this project and all projects it depends on.
>classes - Assembles main classes.
>clean - Deletes the build directory.
>**jar - Assembles a jar archive containing the main classes.**
>testClasses - Assembles test classes.

`./gradlew build` produces following jars in `build/libs`

```
despector-0.1.0-SNAPSHOT-base.jar
despector-0.1.0-SNAPSHOT.jar
despector-0.1.0-SNAPSHOT-javadoc.jar
despector-0.1.0-SNAPSHOT-sources.jar
```

**Comment by AMV007** [comment]
yes. all compiling, sory my mistake

**Comment by AMV007** [comment]
when trying to build  there is error in javadoc
building under ubuntu 18

log:
https://gradle.com/s/dcatodffuv4fu

**Comment by SubOptimal** [comment]
What steps have you done to get `./gradlew build` running with your JDK? As the default wrapper (4.1) does not support JDK 11.

**Comment by AMV007** [comment]
nvm, it's jdk11 bug, sorry for bothering

**Comment by SubOptimal** [comment]
For anyone interested I pushed changes for a build using Java 11 to branch
https://github.com/SubOptimal/Despector/tree/gradle_upgrade
