### ISSUE TITLE
Despector cannot handle duplicate fields

### ISSUE THREAD

**Issue by mikroskeem** [Deamon5550/Despector#7]
```
Exception in thread "main" java.lang.IllegalArgumentException: Duplicate field a
	at org.spongepowered.despector.ast.type.TypeEntry.addField(TypeEntry.java:321)
	at org.spongepowered.despector.decompiler.BaseDecompiler.decompile(BaseDecompiler.java:181)
	at org.spongepowered.despector.decompiler.JarWalker.scanClassFile(JarWalker.java:81)
	at org.spongepowered.despector.decompiler.JarWalker.scanJar(JarWalker.java:72)
	at org.spongepowered.despector.decompiler.JarWalker.walk(JarWalker.java:55)
	at org.spongepowered.despector.Despector.main(Despector.java:203)
```

Not **that** important, but fixing this means Despector is step closer to decompile obfuscated code :smile:

**Comment by jamierocks** [comment]
This issue here is that Despector only uses [field names](https://github.com/Despector/Despector/blob/master/src/main/java/org/spongepowered/despector/ast/type/TypeEntry.java#L313), when a field can (in bytecode) exists with a different type, but same name
